### ISSUE TITLE
jaeger ui no data

### ISSUE THREAD

**Issue by luojianlong** [kubewharf/kelemetry#178]
### Steps to reproduce

jaeger ui page error: No trace results. Try another query.

 kelemetry-informers container log error: level=error msg="query discovery API failed: unable to retrieve the complete list of server APIs: custom.metrics.k8s.io/v1beta1: the server is currently unable to handle the request" cluster=cluster1 mod=discovery

### Kelemetry version

v0.2.4

**Comment by SOF3** [comment]
Discovery API is returning error because custom metrics server was not cleanly uninstalled. You will notice the same problem with other controllers that use the Discovery API, e.g. your namespaces will be stuck at terminating because namespace controller cannot discover resources.

- If you still need the custom metrics server, you can fix the installation; see https://stackoverflow.com/a/75266326/3990767
- If you don't need it anymore, just uninstall it with `kubectl delete apiservices v1beta1.custom.metrics.k8s.io`.

See https://github.com/helm/helm/issues/6361 for a similar issue.
